title: Custom Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
remote_theme: tuur29/pages-themes-cayman
color:
  header: "#000"
  gradient_left: "#fff000"
  gradient_right: "#fff"